### PR TITLE
Test and deployment to Maven Central with Github Actions

### PR DESCRIPTION
**Pull request by MaximFischuk**

### CODE REVIEW

**Comment by StanislavBreadless** [comment]
It seems that there are no logs from tests:
https://github.com/zksync-sdk/schnorr-musig-sdk-java/runs/2305649619

Are you sure they are run?

**Comment by MaximFischuk** [comment]
> It seems that there are no logs from tests:
> https://github.com/zksync-sdk/schnorr-musig-sdk-java/runs/2305649619
> 
> Are you sure they are run?

Sure, Gradle prints result of test and output prints (if it exists), This project has no any tests with print to std output, only asserts

**Comment by StanislavBreadless** [comment]
> > It seems that there are no logs from tests:
> > https://github.com/zksync-sdk/schnorr-musig-sdk-java/runs/2305649619
> > Are you sure they are run?
> 
> Sure, Gradle prints result of test and output prints (if it exists), This project has no any tests with print to std output, only asserts

Maybe add some logs? It is hard to distinguish the situation when the tests are running and when they are not.

**Comment by MaximFischuk** [comment]
> > > It seems that there are no logs from tests:
> > > https://github.com/zksync-sdk/schnorr-musig-sdk-java/runs/2305649619
> > > Are you sure they are run?
> > 
> > 
> > Sure, Gradle prints result of test and output prints (if it exists), This project has no any tests with print to std output, only asserts
> 
> Maybe add some logs? It is hard to distinguish the situation when the tests are running and when they are not.

It is needless, because gradle will fail build on test when some assert failed
```
> Task :test

SchnorrMusigTest > test() FAILED
    java.lang.UnsatisfiedLinkError at SchnorrMusigTest.java:27

SchnorrMusigTest > testMultiple() FAILED
    java.lang.UnsatisfiedLinkError at SchnorrMusigTest.java:27

SchnorrMusigTest > testSingle() FAILED
    java.lang.UnsatisfiedLinkError at SchnorrMusigTest.java:27

3 tests completed, 3 failed

> Task :test FAILED

FAILURE: Build failed with an exception.
```

**Pull request merged**
